services:
  factory-api-server:
    build:
      context: ./bin/server
      dockerfile: Dockerfile
    container_name: factory_api_server  
    env_file:
      - ./bin/server/.env
    ports:
      - "8002:8002"      
    networks:
      - shared-network  
  factory-api-consumer:
    build:
      context: ./bin/consumer
      dockerfile: Dockerfile
    container_name: factory_api_consumer
    env_file:
      - ./bin/consumer/.env
    networks:
      - shared-network   

networks:
  shared-network:
    external: true
    name: global-infra-net    