services:
  document-state-worker:
    build:
      context: ./bin/worker
      dockerfile: Dockerfile
    container_name: document_state_worker
    env_file:
      - ./bin/worker/.env
    networks:
      - shared-network
  document-state-cache:
    build:
      context: ./bin/cache
      dockerfile: Dockerfile
    container_name: document_state_cache
    env_file:
      - ./bin/cache/.env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: global-infra-net