services:
  document-api-publisher:
    build:
      context: ./bin/publisher
      dockerfile: Dockerfile
    container_name: document_api_publisher
    env_file:
      - ./bin/publisher/.env
    networks:
      - shared-network
      
  document-api-server:
    build:
      context: ./bin/server
      dockerfile: Dockerfile
    container_name: document_api_server  
    env_file:
      - ./bin/server/.env
    ports:
      - "8001:8001"      
    networks:
      - shared-network  

networks:
  shared-network:
    external: true
    name: global-infra-net    