services:

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    ports:
      - "9333:9333"   # Master + Master UI
      - "9340:9340"   # Volume
      - "8888:8888"   # Filer UI
      - "8333:8333"   # S3
      - "7333:7333"   # WebDAV
      - "23646:23646" # ★ Admin UI
    command: >
      mini
        -dir=/data
        -ip=seaweedfs
        -ip.bind=0.0.0.0
        -master.port=9333
        -volume.port=9340
        -filer.port=8888
        -s3.port=8333
        -admin.port=23646
    volumes:
      - seaweedfs_data:/data
    restart: unless-stopped
    networks:
      - shared-network
      
volumes:
  seaweedfs_data:

networks:
  shared-network:
    external: true
    name: global-infra-net