services:
  api-factory-consumer:
    container_name: api_factory_consumer
    build:
      context: ./infrastructure/consumer
      dockerfile: Dockerfile
    image: rey-sudo/api-factory-consumer:latest
    restart: always
    env_file:
      - .env
    network_mode: "host" 