services:
  api-document-publisher:
    container_name: api_document_publisher
    build:
      context: ./infrastructure/publisher
      dockerfile: Dockerfile
    image: rey-sudo/api-document-publisher:latest
    restart: always
    env_file:
      - .env
    network_mode: "host"    