services:
  postgres-global:
    image: postgres:17-alpine
    container_name: postgres_global
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=main_db

      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - shared-network
    deploy:
      resources:
        limits:
          memory: 1gb

networks:
  shared-network:
    external: true
    name: global-infra-net

volumes:
  postgres_data:
    driver: local