services:
  document-processor-worker:
    build:
      context: ./bin/worker
      dockerfile: Dockerfile
    container_name: document_processor_worker
    env_file:
      - ./bin/worker/.env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: global-infra-net