services:
  document-processor-worker:
    build:
      context: ./bin/worker
      dockerfile: Dockerfile
    container_name: document_processor_worker
    env_file:
      - ./bin/worker/.env
    networks:
      - shared-network
  document-processor-tiptap:
    build:
      context: ./bin/tiptap
      dockerfile: Dockerfile
    container_name: document_processor_tiptap 
    env_file:
      - ./bin/tiptap/.env
    ports:
      - "7001:7001"      
    networks:
      - shared-network 

networks:
  shared-network:
    external: true
    name: global-infra-net